IMGSZ = 1024 # size of the image that is analysed
CONFIDENCE = 0.7 # minimum confidence that a prediction needs to be counted as a droplet
MAX_DETECT = 500 # maximum amount of droplets that can be detected in the image
PIXEL_RATIO = 1
UNIT = "px"
TEST_IMAGE = "snapshot_56.jpg"
WEIGHT = "best_9.pt"
OMIT_BORDER_DROPLETS = True
SAVE = True # only for get_boxes.py